language: java
services:
  - docker
env:
  global:
    - GCP_PROJECT_ID=devops-eksamen-295808
    - IMAGE=gcr.io/devops-eksamen-295808/devops-eksamen
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
    - secure: piNl4zVEH2ZvWzPtkMNdUW1oiyWGWmBIi+RCYC4rQHYuEo48B0IbyL0wYUDiFpXqw5c8MOvNEiMb9PGWdZSERo+8H92TgZMDBdFxgx1zlP0lmmpPk9FSdxeC0YbEZwZm6k55JReT1bQ6v79zuVTq+xLYZWxBhs+HIBPjhx8KjVgVj7gaol8yRIsibWPSiReToqgmVOhnnhDdPmWXP72MHAgCy6E4MA0UmVBVptb4Ebfxyr35sIFARHgQK2veBY9V8GzzypCd+oE4FOydPDtA7J0/RGbsV6/XmV+eYfUT714UXS+9yZWCW4AtEYqsYIZtso0i52wuusGiqtgwzR4CS+4mgjXiinaig6ynBoWv9XhPeOS7V2jdbK19eKidIf6x7gu3H5okSxufp5zVLS/0MsDnfby4AJlEYKE9xN4LmQcjC4rwpQ+yX2xk2K5eCSUpll1EyH905n1eMdOglwjA9jnIjU6m9ea1o6PPYw072zbTvK+2pS+W4GX6uF0MYGMvRv3I1cjuzl0gMJZm4dhl1wFGDf3S4RphjLYFiEChexUokGJ40bcZ8NT1D2Eq2TxvKGQ09tfmVaIDLmy7rTAyPHXJMBf8/gZsPwmrlQ//SiBuLEW+traP/IqSL3MX1m7OI0IQ/wCY+OxDHwn5CPSpOeVEIhNU4oXSDOe8ClyCHC4=
    - secure: JN0r8zy9KDyJSla/jRh42yy8hGLmVxYh9kvvD1mcLun2fBzGnIANRqSx2xoEbDkna7vR1hCgSRSIWjBRM8yA7yqaN4b0cS0kY0RDkHY6q/8rj3K9QV/Hz9ZTkejowkOE//OMlimCiUOsqZMuZLXvlTTgcRTOMv+BEt2kOY1uDO5Nbvm7qw0t2ObDjrY7S1oGa/qLWaf0Q/lm6gWGxp7UJs7TsT2CgNKqCzbTFV1ZsPqAgyN17EOfXC9VBolGKIDNBuMclP9yrzwsprhXw/mlOdNc87hm/QwG3kNNjjPDXq86qequajk9735r2aIcGROemvj8IqHg756VcQ76TmuFazeswdCVl2zGNTC1VQ1/IGmbX9XUxi6datrcfs7bo/3wUBmIGV9HK+lLW/Z8bYVYOP5V0n4QRKfZIfMHZOzvGl6euARKlC+ctgFFXt+uuUxWtoHM192Sk3fdJIXVE/mWe+8iPCmljtyt7c7sH8Tu9JnwiPRZ66Y+uHju0GF69BXS1rbTjbatYFduSfuOFUREOKAJKE5+n5Hoc+j5nz6LDbSbaPtZFFAth/ktc3w/IwMwPiAkUt6ewwNQwwY4MffkZB2G+VAYppuj5ngM+0OlBz7ZWfSAqbY+4hgCzeXyi7pzFwR/Y7KMu9mg0IFm3OBufWYS4cTbkp/FmbvQjLX2glY=

before_install:
    - openssl aes-256-cbc -K $encrypted_08046dc9db46_key -iv $encrypted_08046dc9db46_iv -in GCP-key.json.enc -out GCP-key.json -d
    - curl https://sdk.cloud.google.com | bash > /dev/null
    - source "$HOME/google-cloud-sdk/path.bash.inc"
    - gcloud auth configure-docker
    - gcloud config set project "${GCP_PROJECT_ID}"
    - gcloud components install beta
    - gcloud auth activate-service-account --key-file=GCP-key.json
script:
  - |-
    set -ex;
    docker build -t "${IMAGE}:${TRAVIS_COMMIT}" . && \
    docker push "${IMAGE}:${TRAVIS_COMMIT}" && \
    set +x