language: java
services:
- docker
env:
  global:
  - GCP_PROJECT_ID=devops-eksamen-295808
  - IMAGE=gcr.io/devops-eksamen-295808/devops-eksamen
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
  - secure: Be8Y2Akq0P4/q1LU5ou/QDgWI79HJ2IW/O0geUc1CF9benEtwXmvLLCSD730xFXWtyP4I/Slfgcaz+kn9rihAn9mWkEmHcJfwQBfbNa2lm0H3wpdOu3epRS1vqe6hmguWGHuM07jYNQ3lfiWZ5v2tdgGC+nCYi/gu12cREtk0CGudE6wqTzchebmGhjPikhLCovNVx4xWWoODqXAW8heTn56TIAXLEwcI/bbIsGOb0gvDUJjLSMXj/fpHn5k/2RGMu8G9siHQOPMeqX0Xj9gav5hiaVPg5GfXi9lhQI5e5Ssr/jHuZ/gYGqQL8jgZr+lSD5W3/LgilpCyu8tt3X5a2dQoMpCUIbg2uUXe63UnNvC9XxQX6pjyxuGGE5pz5M0g+sJKj83RMngNJj1wNAy+bZqFotFDbWTC8AsA8G7MMOePSaat8/FBvMgLxE1QGGV/7QHB69m3qnhi4yCivp2DT+yDTcPvHXVTNIFE6ZUTOOOVAeTpNHJS4pnwEDTE17aor7mrT3DUEfXMaoKHpvq4UGVr4habmwmCnB+wzzMsWToQj2Qo8Uis86WT2LT4L4AR3GW2MMXMVTyClaH5PoY3DgrLhgcsLQ7M1T6TnhaazKHEzBdgfPHn/xUXD7jdH/cl3pkPCGOoIROCR+0LLj38GJNQVwEH2EtjdHdLTE8pPE=
  - secure: I+HkIWSgWh69p9s9JFN7oBH9QUkb7lgcMIh0iPLVE6PniG3Yoqj0XBgW3oOmkDahU2NdPEGA892lo2ifj+x2WIpWFoOr3X32ByRZn79uvVhlngKUSWzlGtkFUONsoKXdbzHdAam9UE2ls71yC0jprss/A8F55Ix2BQa2dUVNIvvehMcrbQfRlwH0EAg3hwFgA3RZ1lv6Nn5Mi0p7z3cEWfn1tYkHAayka6RSGp421boyWSBmn4Qg2eAMRwSPWJlFH/p3SGd2BQt1WK0XsADNBfr8zjvTZ+j83n0n8d4s3MOWsJy/grM9anMn18rNnbXlbRGHqxKfn2FmqrADP4QZBWVRRewgJ6Hi/1DVro9YVXgGxNk/GTMBNp/w6vrJwAzGObI/0zcRjk54eoDLtfLA/WVJRnE1d2/mexa3iXXagFI5HwrrNfcev3T+uU+WcVhTlEVeXPsn9cCbWKIOSOOemRlo/zIn0SFVdwz7Sy51utN9QgjjQkv6Jrflu0sqYimBpiAj22lTn5zjOe9kbLvqNDaJSu7KW9W8MIFmgF9egRa/i24vBIuQZZ/I95plilXoP3bBXvim8xGsTaOCDHzy308gw9cPHa5MNfcCnQ0eGQWuXwwlP/74e8UuvyrGal6KK5epV60iRmETTA1q7c01ogG/0ybBxnlgX89csS+zSEo=
before_install:
- openssl aes-256-cbc -K $encrypted_08046dc9db46_key -iv $encrypted_08046dc9db46_iv
  -in GCP-key.json.enc -out GCP-key.json -d
- curl https://sdk.cloud.google.com | bash > /dev/null
- source "$HOME/google-cloud-sdk/path.bash.inc"
- gcloud auth configure-docker
- gcloud config set project "${GCP_PROJECT_ID}"
- gcloud components install beta
- gcloud auth activate-service-account --key-file=GCP-key.json
script:
- |-
  set -ex;
  docker build -t "${IMAGE}:${TRAVIS_COMMIT}" . && \
  docker push "${IMAGE}:${TRAVIS_COMMIT}" && \
  set +x
